### ISSUE TITLE
Question related to other dependecies

### ISSUE THREAD

**Issue by elorzafe** [daminetreg/emscripten-example#1]
Thanks for sharing this! I was trying to `find_package`  but when I use your cmake command it seems that it cant find it. Did you have an issue like that?

Thanks!

**Comment by daminetreg** [comment]
Hi @elorzafe,

Oh sorry I didn't see your request here.

This example is pretty old and not really usable. I couldn't even remember having it online. You can use the library here to do XmlHttpRequest from C++, it also works in non-webassembly platfrom with a beast backend : https://nxxm.github.io/xxhr/html/index.html

You can also head up towards my js::bind library, which has a easy to grasp example like the one in this repo : https://github.com/nxxm/js-bind, see example https://github.com/nxxm/js-bind/blob/master/test/bind.html

You can use any of these libs with [nxxm](https://nxxm.github.io) which will ship any dependencies (including emscripten) in your own project or just compile them directly with nxxm to play with them : `nxxm .` is enough.

**Comment by daminetreg** [comment]
If you want any real-time help you are welcome on our gitter community  : [Gitter community](https://gitter.im/nxxm/community)

**Comment by elorzafe** [comment]
@daminetreg I will!
